apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: myhomelab-ingress
spec:
    ingressClassName: traefik
    rules:
        - host: myhomelab.damonhome.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: myhomelab
                            port:
                                number: 80
