apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: catch-all-root
    annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: web # port 80
spec:
    rules:
        - http: # 唔寫 host = 代表任何來源（包括純 IP）
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: myhomelab-service
                            port:
                                number: 80
